// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJP2qS9kCCEHmmGK5fTbpUHIRq0v60jss',
    appId: '1:458445587081:web:dbb94509b5f153f4287c58',
    messagingSenderId: '458445587081',
    projectId: 'do-now-app-12345',
    authDomain: 'do-now-app-12345.firebaseapp.com',
    storageBucket: 'do-now-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqH3srtQALSgyRwPvrnrLP6qBgvz_D_s',
    appId: '1:458445587081:android:a43b3bf1083d45c2287c58',
    messagingSenderId: '458445587081',
    projectId: 'do-now-app-12345',
    storageBucket: 'do-now-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qEQVnad-dNxM-oko4teN1NusZBcrSe8',
    appId: '1:458445587081:ios:10864c4d8f52338b287c58',
    messagingSenderId: '458445587081',
    projectId: 'do-now-app-12345',
    storageBucket: 'do-now-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.doNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qEQVnad-dNxM-oko4teN1NusZBcrSe8',
    appId: '1:458445587081:ios:10864c4d8f52338b287c58',
    messagingSenderId: '458445587081',
    projectId: 'do-now-app-12345',
    storageBucket: 'do-now-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.doNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJP2qS9kCCEHmmGK5fTbpUHIRq0v60jss',
    appId: '1:458445587081:web:ae7a3aa6b8524aaa287c58',
    messagingSenderId: '458445587081',
    projectId: 'do-now-app-12345',
    authDomain: 'do-now-app-12345.firebaseapp.com',
    storageBucket: 'do-now-app-12345.firebasestorage.app',
  );
}
